Repository caicloud/rudder-client, pull requests merged in 2018-12, with the labels that each got.

#12 chore: remove unuseful vendor
  Gopkg.toml
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/S

#13 feat: treat all failedCreate as Error
  Gopkg.lock
  status/apps/v1/daemonset.go
  status/apps/v1/statefulset.go
  vendor/github.com/caicloud/clientset/pkg/apis/release/v1alpha1/known_keys.go
  vendor/github.com/caicloud/clientset/util/event/event.go
  vendor/github.com/caicloud/clientset/util/status/pod_event.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/M

#14 fix(serializer): fix serializer to chart
  serializer/apps/v1/deployment.go
  serializer/apps/v1beta1/deployment.go
  serializer/apps/v1beta2/deployment.go
  serializer/core/v1/service.go
  serializer/extensions/v1beta1/deployment.go
  serializer/factory.go
  serializer/universal/config.go
  serializer/universal/container.go
  serializer/universal/controller.go
  serializer/universal/interface.go
  serializer/universal/pod.go
  serializer/universal/volume.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XL

#15 feat(status): predict resource status from long running event firstly
  Gopkg.lock
  status/apps/v1/daemonset.go
  status/apps/v1/deployment.go
  status/apps/v1/longrunning.go
  status/apps/v1/statefulset.go
  status/apps/v1/types.go
  status/apps/v1/universal.go
  vendor/github.com/caicloud/clientset/util/status/pod_event.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/L

#16 fix(serializer): make volume and probe 's serializeration more accurately
  serializer/apps/v1/deployment.go
  serializer/apps/v1beta1/deployment.go
  serializer/apps/v1beta2/deployment.go
  serializer/core/v1/service.go
  serializer/extensions/v1beta1/deployment.go
  serializer/universal/container.go
  serializer/universal/controller.go
  serializer/universal/pod.go
  serializer/universal/util.go
  serializer/universal/volume.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/L
