Repository caicloud/rudder-client, pull requests merged in 2019-01, with the labels that each got.

#18 fix(status): correct workload status when it desires zero replicas
  status/apps/v1/longrunning.go
  status/apps/v1/types.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/S

#19 fix: judge status from pods on the first priority
  status/apps/v1/daemonset.go
  status/apps/v1/deployment.go
  status/apps/v1/longrunning.go
  status/apps/v1/statefulset.go
  status/apps/v1/types.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/L

#21 chore(vendor): specify the go-swep version in Gopkg.toml
  Gopkg.toml
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS
